/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M21
 * Generated at: 2017-06-04 17:13:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sistex.cgd.Dao;
import com.sistex.cgd.DaoProduto;
import servico.Ws;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sistex.cgd.Dao");
    _jspx_imports_classes.add("com.sistex.cgd.DaoProduto");
    _jspx_imports_classes.add("servico.Ws");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-br\">\n");
      out.write("    <head>\n");
      out.write("    \t<meta charset=\"utf-8\">\n");
      out.write("    \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    \t<title> Sistema Web De Gerenciamento FastFood </title>\n");
      out.write("    \t<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("    \t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\n");
      out.write("    \t<link href='https://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>\n");
      out.write("    \t<link rel=\"icon\" href=\"img/icon.png\">\n");
      out.write("        <script type=\"text/javascript\" src=\"js/funcoes.js\"></script>\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <!-- CABEÇALHO -->\n");
      out.write("        <header class=\"cabecalho container Home1\">\n");
      out.write("           <a href=\"index.html\"><h1 class=\"logo\"> SISTEC-Especializada em Soluções Digitais </h1></a>\n");
      out.write("           <button class=\"btn-menu bg-gradient\" ><i class=\"fa fa-bars fa-lg\"></i></button>\n");
      out.write("\n");
      out.write("           <nav class=\"menu\" id=\"close1\">\n");
      out.write("               <a class=\"btn-close\"><i class=\"fa fa-times\"></i></a>\n");
      out.write("               <ul>\n");
      out.write("                   <li class=\"home\"><a href=\"index.jsp\">Home</a></li>\n");
      out.write("                   <li class=\"home\"><a href=\"cadastroClientes.jsp\">Cadastro De Cliente</a></li>\n");
      out.write("                   <li class=\"home\"><a href=\"acesso.jsp\">Acesso</a></li>\n");
      out.write("               </ul>\n");
      out.write("           </nav>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <!-- SERVICOS -->\n");
      out.write("         \n");
      out.write("        <main class=\"imagem servicos container\">\n");
      out.write("         \n");
      out.write("                <h1 class=\"bg-titulo\">PRODUTOS</h1>\n");
      out.write("                <form method=\"post\" action=\"acesso.jsp\" onsubmit=\"mensagem();\">\n");
      out.write("                    <div class=\"produtos\">\n");
      out.write("                    ");

                        try{
                            Dao dao = new DaoProduto();
                            out.println(dao.listar());
                        } catch(Exception ex){
                               ex.printStackTrace();
                        }
                    
      out.write("\n");
      out.write("<!--                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/prato.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Prato Personalizado</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("\n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/tropeiro.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Tropeiro</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("\n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/espaguete.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Espaguete</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/salada.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Espaguete</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("                        \n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/refrigerante.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Coca Cola</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("                        \n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/fanta.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Coca Cola</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("                        \n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/cocazero.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Coca Cola</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("                        \n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/prato1.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Coca Cola</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("                        \n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/prato2.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Coca Cola</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("                        \n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/cocazero.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Coca Cola</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("                        \n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/prato1.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Coca Cola</figcaption>\n");
      out.write("                        </figure>\n");
      out.write("                        \n");
      out.write("                        <figure class=\"figure\" >\n");
      out.write("                            <a href=\"acesso.jsp\"><img class=\"prato\" src=\"img/prato2.png\" alt=\"...\" class=\"img-thumbnail\"></a> \n");
      out.write("                            <figcaption class=\"figure-caption\">Coca Cola</figcaption>\n");
      out.write("                        </figure>-->\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("<!--                      \n");
      out.write("                    <div class=\"newsletter container bg-grey botaopedido\">\n");
      out.write("                        <button type=\"submit\" class=\"bg-white radius campo\">Solicitar Pedido</button>\n");
      out.write("                    </div>\n");
      out.write("                    -->\n");
      out.write("                </form>\n");
      out.write("        </main>\n");
      out.write("\n");
      out.write("        <!-- RODAPÉ -->\n");
      out.write("        <footer class=\"rodape container bg-gradient\">\n");
      out.write("          <div class=\"social-icons\">\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-google\"></i></a>\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-envelope\"></i></a>\n");
      out.write("          </div>\n");
      out.write("          <p class=\"copyright\">\n");
      out.write("            Copyright © SISTEX 2016. Todos os direitos reservados - Desenvolvido Por Jean Carlos Penas.\n");
      out.write("        </footer>\n");
      out.write("        <!-- JQUERY-->\n");
      out.write("\t\t\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\t$(\".btn-menu\").click(function(){\n");
      out.write("\t\t\t\t$(\".menu\").show();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$(\".btn-close\").click(function(){\n");
      out.write("\t\t\t\t$(\".menu\").hide();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\t</body>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
